name: reusable
on:
  workflow_call:
  workflow_dispatch:
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello from tsibley's fork"
      - run: echo "github=$json"
        env:
          json: |
            ${{ toJSON(github) }}
      - run: echo "job=$json"
        env:
          json: |
            ${{ toJSON(job) }}
      - run: echo "env=$json"
        env:
          json: |
            ${{ toJSON(env) }}
