name: Testing that the GITHUB_TOKEN has enough permissions
on: workflow_dispatch
jobs:
  rebuild-docker-image:
    runs-on: ubuntu-latest
    steps:
    - run: gh workflow run ci.yml --repo nextstrain/docker-base
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN_NEXTSTRAIN_BOT_WORKFLOW_DISPATCH }}
