name: workflow_call
on:
  workflow_call:
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "github=$json"
        env:
          json: |
            ${{ toJSON(github) }}
      - run: echo "job=$json"
        env:
          json: |
            ${{ toJSON(job) }}
      - run: echo "env=$json"
        env:
          json: |
            ${{ toJSON(env) }}
